version: '3.2'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis:3.2-alpine
  django:
    build:
      context: .
      dockerfile: ./infra/django/Dockerfile
      args:
        REQUIREMENTS_FILE: dev.txt
    image: gifz_api
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static:/_static
      - media:/_media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file: ./envs/.env.dev
volumes:
  pg-data:
    driver: local
  static:
    driver: local
  media:
    driver: local
